services:
  server:
    build:
      context: ./server
    ports:
      - 3000:3000
    environment:
      - PORT=3000
  client:
    build:
      context: ./client
      target: runner
    ports:
      - 80:80
    depends_on:
      - server