services:
  - type: web
    name: client
    runtime: docker
    dockerfilePath: ./client/Dockerfile
    port: 80
  - type: web
    name: server
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    port: 3000